version: "3.8"

services:
  app:
    container_name: vm_app
    build: ./
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn src.__init__:app --host 0.0.0.0 --port 9000'
    volumes:
      - ./src:/src
      - ./runserver.py:/src/runserver.py
      - ./.env:/src/.env
    ports:
      - ${APP_HOST_PORT}:9000
    restart: always
    env_file:
      - .env
  db:
    container_name: vm_app_postgres
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_HOST_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always